version: "3.7"

services:
  redis:  
    image: redis:latest
    command: 
      - redis-server
      - redis.conf
      - --requirepass 
      - ${REDIS_PASS}
      - --appendonly yes
    volumes:
      - ./data/redis:/data

  frontend:
    image: lightning-swap-frontend:latest
    build: ./frontend
    container_name: lightning-swap-frontend
    ports:
      - 4173:4173
    environment:
      - VITE_VINCENT_BACKEND=${VITE_VINCENT_BACKEND}
      - VITE_TITLE=${VITE_TITLE}
    restart: on-failure
    stop_grace_period: 1m

  backend:
    image: lightning-swap-backend:latest
    build: ./backend
    container_name: lightning-swap-backend
    ports:
      - 1536:1536
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS}
      
      - LND_HOST=${LND_HOST}
      - LND_MACAROON=${LND_MACAROON}
      
      - SWAP_SERVICE_FEERATE=${SWAP_SERVICE_FEERATE}
      - SWAP_MAX_AMOUNT=${SWAP_MAX_AMOUNT}
      - SWAP_MIN_AMOUNT=${SWAP_MIN_AMOUNT}

      - LNBITS_HOST=${LNBITS_HOST}
      - LNBITS_WEBHOOK_URL=${LNBITS_WEBHOOK_URL}
      - LNBITS_MAIN_WALLET_ADMIN_KEY=${LNBITS_MAIN_WALLET_ADMIN_KEY}
      - LNBITS_MAIN_WALLET_INVOICE_KEY=${LNBITS_MAIN_WALLET_INVOICE_KEY}

      - LNBITS_SPLIT_WALLET_ADMIN_KEY=${LNBITS_SPLIT_WALLET_ADMIN_KEY}
      - LNBITS_SPLIT_WALLET_INVOICE_KEY=${LNBITS_SPLIT_WALLET_INVOICE_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data/backend/database.db:/root/vinci/data/database.db
      - ./backend:/app
    restart: on-failure
    stop_grace_period: 1m